services:
  #The Python server 
  api-service:
      #Locate the dockerfile
      build:
        dockerfile: Dockerfile
        context: ./api-service
      environment:
        - port=5000
      # Creta a shared volume
      volumes:
        - ./api-service:/app
      #Map the port 5000 on the container to the port 5000 on the host machine
      ports:
        - 5000:5000
  #The Angular server
  client:
      #Locate the dockerfile
      build:
        dockerfile: Dockerfile
        context: ./client
      # Creta a volume with all the dependencies (just for optimization)
      # And a shared volume
      volumes:
        - /app/node_modules 
        - ./client:/app
      #Set the environment variables
      environment:
        - NG_APP_GITPOD_WORKSPACE_URL=${GITPOD_WORKSPACE_URL}
        - port=4200
      #Map the port 4200 on the container to the port 4200 on the host machine
      ports:
        - 4200:4200
     