services:
  api-service:
      build:
        dockerfile: Dockerfile
        context: ./api-service
      environment:
        - PORT=5000
      volumes:
        - ./api-service:/app
      ports:
        - 5000:5000
  client:
      build:
        dockerfile: Dockerfile
        context: ./client
      volumes:
        - /app/node_modules 
        - ./client:/app
      environment:
        - PORT=5000
      ports:
        - 4200:4200
     