services:
  api-service:
      build:
        dockerfile: Dockerfile
        context: ./api-service
      environment:
        - PORT=5000
      volumes:
        - ./api-service:/app
      ports:
        - 5000:5000